# Created with YamlCreate.ps1 v2.2.12 $debug=NVS1.CRLF.5-1-19041-3693.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: Cisco.Anyconnect
PackageVersion: 4.10.05111
InstallerType: msi
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://bluelink.ca/ftp/CiscoVPN/anyconnect-win-permalink.msi
  InstallerSha256: 2C02653DE21B479481984A3D4C3091E6F849EBF85B670BE71662D899C5C27B5C
  ProductCode: '{4C500292-8BC1-4164-936E-15D2EA5821F2}'
ManifestType: installer
ManifestVersion: 1.5.0
