# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: Treexy.OmnifyHotspot
PackageVersion: 5.1.0.1
InstallerType: exe
InstallerSwitches:
  Silent: /qn
  SilentWithProgress: /qb
  Custom: /norestart
UpgradeBehavior: install
ProductCode: '{040A2850-AA91-4C5F-94B1-32C3FF8E1620}'
Installers:
- Architecture: neutral
  InstallerUrl: https://treexy.com/media/m2dl1c1w/omnifyhotspotfreesetup.exe
  InstallerSha256: B6465315F3679A48F46F4D800A79E7F75F6F17700AEA53E10D2A4C63FB4D53DC
ManifestType: installer
ManifestVersion: 1.6.0
