# Created with YamlCreate.ps1 v2.2.12 $debug=QUSU.CRLF.5-1-19041-3693.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.5.0.schema.json

PackageIdentifier: Altium.AltiumDesigner
PackageVersion: 22.11.1
PackageLocale: en-US
Publisher: Altium
# PublisherUrl: 
# PublisherSupportUrl: 
# PrivacyUrl: 
# Author: 
PackageName: AltiumDesigner
# PackageUrl: 
License: Proprietary
# LicenseUrl: 
# Copyright: 
# CopyrightUrl: 
ShortDescription: AltiumDesigner
# Description: 
# Moniker: 
# Tags: 
# ReleaseNotes: 
# ReleaseNotesUrl: 
# PurchaseUrl: 
# InstallationNotes: 
# Documentations: 
ManifestType: defaultLocale
ManifestVersion: 1.5.0
