# Created with YamlCreate.ps1 v2.2.12 $debug=NVS1.CRLF.5-1-19041-3693.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.5.0.schema.json

PackageIdentifier: KingstVIS.KingstVIS
PackageVersion: 3.6.4
InstallerType: nullsoft
UpgradeBehavior: install
Installers:
- Architecture: x64
  InstallerUrl: https://res.kingst.site/kfs/KingstVIS_v3.4.2.exe
  InstallerSha256: 6B6CCFF743988E9A5B9028F4009C14AF916227E7F87B4151DCFA4141D9A51C3A
ManifestType: installer
ManifestVersion: 1.5.0
