# Created with YamlCreate.ps1 v2.4.1 $debug=NVS2.CRLF.5-1-19041-4648.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json

PackageIdentifier: STMicroelectronics.SPC5Studio
PackageVersion: 5.8.1
PackageLocale: en-US
Publisher: STMicroelectronics
# PublisherUrl:
# PublisherSupportUrl:
# PrivacyUrl:
# Author:
PackageName: SPC5Studio
# PackageUrl:
License: MIT
# LicenseUrl:
# Copyright:
# CopyrightUrl:
ShortDescription: SPC5Studio
# Description:
# Moniker:
# Tags:
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.6.0
