# Created using wingetcreate 1.6.1.0
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json

PackageIdentifier: GiulioSorrentino.wxBriscola
PackageVersion: 0.6.3
InstallerType: wix
Dependencies:
  PackageDependencies:
  - PackageIdentifier: Microsoft.VCRedist.2015+.x64
ProductCode: '{76833DA3-34C1-49B0-A918-8A1825DD50FE}'
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/numerunix/wxBriscola-for-Windows/releases/download/0.6.3/wxBriscola-0.6.3-1-amd64.msi
  InstallerSha256: 3CF74EC7AD5F7E39807EBB6C699D8965F6591D3516DFF3951C0EE309ED8F1BFF
ManifestType: installer
ManifestVersion: 1.6.0
